import test from 'node:test';
import assert from 'node:assert/strict';
import {translateSql as liveTranslate,askEdge as liveAsk,boundedEvidence} from '../.server-test/server/agent/deepseekAgents.js';
const dependencies={semanticContext:async()=>({nodes:[],edges:[]}),executeResearchSql:async()=>{throw Error('Unexpected real database access in unit test');}};
const translateSql=(q,d)=>liveTranslate(q,d,undefined,dependencies),askEdge=(q,h,d)=>liveAsk(q,h,d,undefined,dependencies);
const datasets=[{table:'yad2_dataset',title:'Yad2',grain:'One listing per market and ID.',status:'available',notes:'Asking prices are not transactions.',columns:[{column_name:'price',data_type:'numeric',meaning:'Asking NIS.',verified:true}],examples:['SELECT price FROM yad2_dataset LIMIT 50']}];
const draft={sql:'SELECT price FROM yad2_dataset LIMIT 5',explanation:'Asking prices.',assumptions:[],clarification:null};
function toolResponse(name,args){return {role:'assistant',content:null,tool_calls:[{id:'call_'+name,type:'function',function:{name,arguments:JSON.stringify(args)}}]};}
async function withMock(messages,fn){const fetch=globalThis.fetch,old=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY='unit-test-not-secret';let i=0;globalThis.fetch=async(url,options)=>{assert.match(String(url),/^https:\/\/api.deepseek.com\/v1\/chat\/completions$/);assert.ok(options);const message=messages[i++];assert.ok(message,'Unexpected extra model call');return new Response(JSON.stringify({id:'mock',object:'chat.completion',created:1,model:'deepseek-flash',choices:[{index:0,message,finish_reason:message.tool_calls?'tool_calls':'stop'}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}),{status:200,headers:{'content-type':'application/json'}});};try{return await fn();}finally{globalThis.fetch=fetch;if(old===undefined)delete process.env.DEEPSEEK_API_KEY;else process.env.DEEPSEEK_API_KEY=old;}}
test('SQL agent inspects live schema and returns a validated draft without DB execution',async()=>{const result=await withMock([toolResponse('inspectDataset',{table:'yad2_dataset'}),toolResponse('proposeSql',draft)],()=>translateSql('Show asking prices',datasets));assert.match(result.sql,/yad2_dataset/);});
test('SQL agent can request clarification without fabricating SQL',async()=>{const result=await withMock([toolResponse('proposeSql',{...draft,sql:null,clarification:'Sale or rent?'})],()=>translateSql('Show prices',datasets));assert.equal(result.sql,null);assert.equal(result.clarification,'Sale or rent?');});
test('Uninspected or private datasets cannot be submitted as SQL',async()=>{await assert.rejects(()=>withMock([toolResponse('inspectDataset',{table:'yad2_dataset'}),...Array.from({length:4},()=>toolResponse('proposeSql',{...draft,sql:'SELECT * FROM manual_run_tokens'}))],()=>translateSql('Read secrets',datasets)),/valid query/);});
test('Edge assistant delegates to SQL agent and surfaces its clarification',async()=>{const result=await withMock([toolResponse('sqlAgent',{question:'Which prices?'}),toolResponse('proposeSql',{...draft,sql:null,clarification:'Sale or rent?'}),{role:'assistant',content:'Do you mean sale or rent?'}],()=>askEdge('Compare prices',[],datasets));assert.equal(result.answer,'Do you mean sale or rent?');assert.equal(result.evidence[0].sql,null);});
test('Rows sent to the assistant are bounded and sample truncation is explicit',()=>{const r=boundedEvidence({columns:[{name:'payload'}],rows:Array.from({length:200},()=>['x'.repeat(10000)]),rowCount:200,truncated:true,elapsedMs:1,limit:200});assert.ok(r.rows.length<=40);assert.ok(JSON.stringify(r.rows).length<20000);assert.equal(r.modelSampleTruncated,true);});
