// Browser UI connected to the real workflow service and disposable PostgreSQL.
// No production API requests, records, credentials or paid inference.
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {workflowFixture,listingId,otherListingId} from './workflow-fixture.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');
const server=spawn('python',['-m','http.server','4189','--directory','dist'],{stdio:'ignore'});
const {db,service:s}=await workflowFixture();let browser,failWrite=false,failRead=false;
const neighborhoodId='44444444-4444-4444-4444-444444444444';
try{
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
 await page.route('**/api/**',async route=>{
  const request=route.request(),u=new URL(request.url());let response={},status=200;
  try{
   if(u.pathname==='/api/edge-data')response={mode:'live',areas:[],opportunities:[],generatedAt:'2026-10-05'};
   if(u.pathname==='/api/data-status')response={freshness:[],counts:{}};
   if(u.pathname==='/api/property'){const id=u.searchParams.get('id');assert([listingId,otherListingId].includes(id),'Router must strip section/deal query before API ID');response={tier:'basic',listing:{id,address:id===listingId?'נכס בדיקה א':'נכס בדיקה ב',asking_price_ils:1000000,area_sqm:85,rooms:4,floor:3,url:'https://example.com/search',source_url_kind:'search'},seller:{days_on_market:null,price_reductions:null,lifecycle_evidence:'provisional'},comps:[]};}
   if(u.pathname==='/api/opportunities'){
    if(request.method()==='POST'){
     if(failWrite){response={error:'isolated_write_failed'};status=503;}else{const b=request.postDataJSON();const actions={create_deal:()=>s.createDealForListing(b.listing_id),save_note:()=>s.saveNote(b),update_dd:()=>s.updateDueDiligence(b),save_task:()=>s.saveTask(b),save_scenario:()=>s.saveScenario(b),set_stage:()=>s.setDealStage(b.deal_id,b.stage,b.rejection_reason),next_action:()=>s.updateNextAction(b.deal_id,b.next_action),set_offer:()=>s.setOffer(b.deal_id,b.offer_price_nis),create_dd_item:()=>s.createDdItem(b)};assert(actions[b.action]);response={ok:true,data:await actions[b.action]()};}
    }else if(failRead){response={error:'isolated_read_failed'};status=503;}
    else if(u.searchParams.get('mode')==='deals')response={deals:await s.listDeals()};
    else{response=await s.getDealBundle({dealId:u.searchParams.get('deal_id')||undefined,listingId:u.searchParams.get('listing_id')||undefined});if(!response){response={error:'not_found'};status=404;}}
   }
   if(u.pathname==='/api/neighborhood-map')response={cities:[{city_id:'haifa',name_he:'חיפה',has_transaction_data:true}],neighborhoods:[{neighborhood_id:neighborhoodId,name_he:'אזור בדיקה',city:'חיפה',geometry:null}]};
   if(u.pathname==='/api/neighborhood'){
    const section=u.searchParams.get('section');if(section==='listings'){await new Promise(r=>setTimeout(r,350));if(failRead){response={error:'listing_load_failed'};status=503;}else response={data:[{id:listingId,status:'active',canonical_address:'נכס בדיקה א',asking_price_nis:1000000,area_sqm:85,rooms:4,executed_discount_pct:-10,days_on_market:null}]};}else response={data:section==='summary'?{neighborhood:{},metrics:[],datasets:[]}:[]};
   }
  }catch(e){response={error:e.message};status=400;}
  await route.fulfill({status,contentType:'application/json',body:JSON.stringify(response)});
 });
 await page.goto('http://127.0.0.1:4189/#/property/'+listingId+'?section=deal');await page.getByRole('button',{name:'צור Deal',exact:true}).click();await page.getByRole('heading',{name:'שלב ופעולה הבאה',exact:true}).waitFor();const deal=(await s.getDealBundle({listingId})).deal;
 await page.reload();await page.getByRole('heading',{name:'שלב ופעולה הבאה',exact:true}).waitFor();assert(page.url().includes('section=deal'));
 await page.getByRole('button',{name:'Notes',exact:true}).click();await page.getByLabel('תוכן הערה').fill('שיחה מתועדת');await page.getByLabel('קישור מקור להערה').fill('https://example.com/call');failWrite=true;await page.getByRole('button',{name:'שמור הערה',exact:true}).click();await page.getByRole('alert').filter({hasText:'isolated_write_failed'}).waitFor();assert.equal(await page.getByLabel('תוכן הערה').inputValue(),'שיחה מתועדת');
 failWrite=false;await page.getByRole('button',{name:'Deal',exact:true}).click();await page.getByRole('button',{name:'Notes',exact:true}).click();assert.equal(await page.getByLabel('תוכן הערה').inputValue(),'שיחה מתועדת');await page.getByRole('button',{name:'שמור הערה',exact:true}).click();await page.getByText('שיחה מתועדת',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Due Diligence',exact:true}).click();const item=page.locator('.wf-dd-item').filter({hasText:'אימות המודעה, כתובת מלאה וזמינות'});await item.getByLabel('מצב בדיקה: אימות המודעה, כתובת מלאה וזמינות',{exact:true}).selectOption('verified');await item.getByLabel('ממצאים ותוצאה',{exact:true}).fill('כתובת הושוותה למקור; נדרשת בדיקת זכויות נפרדת');await item.getByRole('button',{name:'שמור בדיקה',exact:true}).click();await page.getByRole('alert').filter({hasText:'verification_requires_findings_and_source'}).waitFor();
 await item.getByRole('button',{name:'הוסף מקור',exact:true}).click();await item.getByLabel('כותרת המקור',{exact:true}).fill('מקור זהות');await item.getByLabel('קישור למקור',{exact:true}).fill('https://example.com/identity');await item.getByLabel('תאריך בדיקת המקור',{exact:true}).fill('2026-10-05');await item.getByRole('button',{name:'שמור בדיקה',exact:true}).click();await page.getByRole('status').filter({hasText:'נשמר בהצלחה'}).waitFor();
 await item.getByRole('button',{name:'פתח משימה להשלמה',exact:true}).click();const task=page.locator('.wf-task-editor');await task.getByLabel('אחראי',{exact:true}).fill('בודק');await task.getByLabel('מועד לביצוע',{exact:true}).fill('2026-10-10');await task.getByLabel('מצב משימה',{exact:true}).selectOption('done');await task.getByLabel('תוצאה / מה נמצא',{exact:true}).fill('תיאום שיחה הושלם');await task.getByRole('button',{name:'שמור משימה',exact:true}).click();await page.locator('.wf-task-list').getByText('תיאום שיחה הושלם',{exact:true}).waitFor();assert.equal((await s.getDealBundle({dealId:deal.id})).dueDiligence.find(x=>x.item_key==='listing_identity').status,'verified');
 await page.getByRole('button',{name:'Deal',exact:true}).click();await page.getByLabel('שם תרחיש',{exact:true}).fill('ללא הלוואה');await page.getByLabel('סכום הלוואה',{exact:true}).fill('0');await page.getByLabel('ריהוט',{exact:true}).fill('10000');await page.getByLabel('עלויות רכישה נוספות ורזרבה',{exact:true}).fill('20000');await page.getByLabel('שכירות חודשית',{exact:true}).fill('4500');await page.getByLabel('מס במכירה',{exact:true}).fill('50000');await page.getByLabel('בדקתי את ההנחות, כולל ערכי אפס',{exact:true}).check();await page.getByRole('button',{name:'חשב ושמור תרחיש',exact:true}).click();await page.getByRole('heading',{name:'תוצאות שמורות — ללא הלוואה',exact:true}).waitFor();
 const base=(await s.getDealBundle({dealId:deal.id})).scenarios[0];assert.equal(base.assumptions.loanAmountNis,0);assert.equal(base.outputs.monthlyDebtServiceNis,0);assert.equal(base.assumptions.furnishingNis,10000);
 await page.getByLabel('תרחיש שמור',{exact:true}).selectOption('');await page.getByLabel('שם תרחיש',{exact:true}).fill('שמרני');await page.getByLabel('סוג תרחיש',{exact:true}).selectOption('conservative');await page.getByLabel('בדקתי את ההנחות, כולל ערכי אפס',{exact:true}).check();await page.getByRole('button',{name:'חשב ושמור תרחיש',exact:true}).click();await page.getByRole('heading',{name:'תוצאות שמורות — שמרני',exact:true}).waitFor();await page.getByLabel('תרחיש שמור',{exact:true}).selectOption(base.id);assert.equal(await page.getByLabel('סכום הלוואה',{exact:true}).inputValue(),'0');await page.getByRole('heading',{name:'תוצאות שמורות — ללא הלוואה',exact:true}).waitFor();
 await page.getByLabel('שלב עסקה',{exact:true}).selectOption('Rejected');await page.getByRole('button',{name:'בטל שינוי שלב',exact:true}).click();assert.equal((await s.getDealBundle({dealId:deal.id})).deal.stage,'Saved');await page.getByLabel('שלב עסקה',{exact:true}).selectOption('Researching');await page.getByRole('button',{name:'שמור שלב',exact:true}).click();await page.getByRole('status').filter({hasText:'נשמר בהצלחה'}).waitFor();
 await s.createDealForListing(otherListingId);await page.goto('http://127.0.0.1:4189/#/deals');await page.locator('.pipeline-card').first().waitFor();await page.getByLabel('השווה מועמד (2–6)',{exact:true}).nth(0).check();await page.getByLabel('השווה מועמד (2–6)',{exact:true}).nth(1).check();await page.getByRole('table').waitFor();await page.locator('.pipeline-card').filter({hasText:'נכס בדיקה א'}).click();await page.getByRole('heading',{name:'שלב ופעולה הבאה',exact:true}).waitFor();assert(page.url().includes('deal_id='+deal.id));assert(page.url().includes('section=deal'));
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Workflow mobile must scroll only its tables, not the page');await page.getByRole('button',{name:'Due Diligence',exact:true}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'DD mobile overflow');await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/workflow-mobile.png',fullPage:true});
 await page.goto('http://127.0.0.1:4189/#/areas?neighborhoodId='+neighborhoodId);await page.getByRole('button',{name:'Listings',exact:true}).click();await page.getByRole('status').filter({hasText:'טוען נתוני אזור'}).waitFor();assert.equal(await page.getByText('No listings are currently mapped to this neighborhood.',{exact:true}).count(),0);await page.getByText('10.0% מתחת למדד',{exact:true}).first().waitFor();failRead=true;await page.getByRole('button',{name:'Overview',exact:true}).click();await page.getByRole('button',{name:'Listings',exact:true}).click();await page.getByRole('alert').waitFor();failRead=false;await page.getByRole('button',{name:'נסה שוב',exact:true}).click();await page.getByText('10.0% מתחת למדד',{exact:true}).first().waitFor();
 assert.deepEqual(errors,[]);console.log('PASS actual PostgreSQL workflow browser acceptance: create/refresh, notes/retry/drafts, DD/evidence, task, zero-loan scenarios/switch/compare, cancelled rejection/stage, candidate comparison, precise pipeline route, mobile and area load/error/retry');
}finally{if(browser)await browser.close();await db.close();server.kill();}
