import { useEffect, useRef, useState } from 'react';
import './DataExplorer.css';
type Column={column_name:string;data_type:string;is_nullable:string;meaning:string;verified:boolean};
type Dataset={table:string;title:string;grain:string;notes:string;source:string;status:string;lastSuccessAt?:string;rowCount?:number;coverage?:string;columns:Column[];examples:string[]};
type Result={columns:{name:string}[];rows:unknown[][];rowCount:number;truncated:boolean;elapsedMs:number};
async function request(body?:object,signal?:AbortSignal){const r=await fetch('/api/ask?mode=data-explorer',{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to load data.');return data;}
const cell=(value:unknown)=>value==null?'NULL':typeof value==='object'?JSON.stringify(value):String(value);
export default function DataExplorer(){
 const [datasets,setDatasets]=useState<Dataset[]>([]),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[sql,setSql]=useState(''),[view,setView]=useState<'preview'|'schema'|'sql'>('preview');
 const [result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[catalogError,setCatalogError]=useState('');
 const active=useRef<AbortController|null>(null),dataset=datasets.find(d=>d.table===selected);
 useEffect(()=>{const control=new AbortController();request(undefined,control.signal).then(d=>{setDatasets(d.datasets);setSelected(d.datasets[0]?.table||'');}).catch(e=>{if(e.name!=='AbortError')setCatalogError(e.message);}).finally(()=>setLoading(false));return()=>{control.abort();active.current?.abort();};},[]);
 async function run(query:string){active.current?.abort();const control=new AbortController();active.current=control;setBusy(true);setError('');setResult(null);try{setResult(await request({sql:query},control.signal));}catch(e:any){if(e.name!=='AbortError')setError(e.message);}finally{if(active.current===control)setBusy(false);}}
 useEffect(()=>{if(!selected)return;const q=`SELECT * FROM public."${selected}" LIMIT 50`;setSql(q);setView('preview');void run(q);},[selected]);
 const shown=datasets.filter(d=>`${d.title} ${d.table} ${d.source}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="data-explorer panel" dir="ltr" aria-label="SQL dataset explorer">
  <header className="dx-header"><div><h2>Dataset explorer</h2><p>Preview collected data, inspect its meaning, and query with SQL.</p></div><span>Read-only · 200-row query limit</span></header>
  {loading?<p role="status">Loading datasets…</p>:catalogError?<p role="alert">{catalogError}</p>:!datasets.length?<p>No research datasets are initialized yet.</p>:<div className="dx-layout">
   <aside className="dx-sidebar"><label htmlFor="dx-search">Available datasets ({datasets.length})</label><input id="dx-search" value={search} placeholder="Find a dataset…" onChange={e=>setSearch(e.target.value)}/><div className="dx-list">{shown.map(d=><button key={d.table} aria-pressed={selected===d.table} className={selected===d.table?'selected':''} onClick={()=>setSelected(d.table)}><strong>{d.title}</strong><small>{d.source} · {d.status}{d.rowCount!=null?` · ${Number(d.rowCount).toLocaleString()} observations`:''}</small></button>)}{!shown.length?<p>No matching datasets.</p>:null}</div></aside>
   <div className="dx-workspace">{dataset?<><h3>{dataset.title}</h3><code className="dx-name">public."{dataset.table}"</code><p>{dataset.grain}</p><p className="dx-note">{dataset.notes}</p>{dataset.coverage?<p>{dataset.coverage}</p>:null}{dataset.lastSuccessAt?<p>Last successful import: {new Date(dataset.lastSuccessAt).toLocaleString()}</p>:null}
    <nav className="dx-tabs" aria-label="Dataset views">{(['preview','schema','sql'] as const).map(v=><button key={v} aria-pressed={view===v} className={view===v?'selected':''} onClick={()=>{setView(v);if(v==='preview')void run(dataset.examples[0]);}}>{v==='schema'?'Semantic layer':v==='sql'?'SQL query':'Data preview'}</button>)}</nav>
    {view==='schema'?<div className="dx-scroll"><table><thead><tr><th>Column</th><th>SQL type</th><th>Nullable</th><th>Meaning</th></tr></thead><tbody>{dataset.columns.map(c=><tr key={c.column_name}><td><code>"{c.column_name}"</code></td><td>{c.data_type}</td><td>{c.is_nullable}</td><td>{c.meaning}{!c.verified?<small className="dx-unverified">Definition pending</small>:null}</td></tr>)}</tbody></table></div>:<>
     {view==='sql'?<div className="dx-editor"><label htmlFor="dx-sql">SQL · SELECT and WITH queries, including joins across available datasets</label><textarea id="dx-sql" spellCheck={false} value={sql} onChange={e=>setSql(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(!busy)void run(sql);}}}/><div className="dx-actions"><button disabled={busy||!sql.trim()} onClick={()=>void run(sql)}>{busy?'Running…':'Run query'}</button><span>Ctrl / ⌘ + Enter</span>{dataset.examples.map((q,i)=><button key={q} disabled={busy} onClick={()=>setSql(q)}>{i===0?'Sample rows':'Example aggregation'}</button>)}</div></div>:null}
     {busy?<p role="status">Loading results…</p>:error?<p role="alert" className="dx-error">{error}</p>:result?<><p className="dx-result" role="status">{result.rowCount} rows · {result.elapsedMs} ms{result.truncated?' · First 200 rows shown; narrow the query to see more.':''}</p><div className="dx-scroll"><table><thead><tr>{result.columns.map((c,i)=><th key={i}>{c.name}</th>)}</tr></thead><tbody>{result.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} title={cell(v)}><span className={v==null?'dx-null':'dx-cell'}>{cell(v)}</span></td>)}</tr>)}</tbody></table></div>{!result.rows.length?<p>No rows match this query. The column schema is shown above.</p>:null}</>:null}
    </>}</>:null}</div>
  </div>}
 </section>;
}
