import { useEffect,useState } from 'react';
import { X } from 'lucide-react';
type Message={role:'user'|'assistant';text:string;evidence?:any[]};
export default function EdgeAgentDrawer({open,onClose}:{open:boolean;onClose:()=>void}){
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[configured,setConfigured]=useState<boolean|null>(null);
 useEffect(()=>{if(!open)return;const c=new AbortController();fetch('/api/ask?mode=edge-agent',{signal:c.signal}).then(r=>r.json()).then(d=>setConfigured(d.configured)).catch(()=>setConfigured(false));return()=>c.abort();},[open]);
 async function ask(){if(busy||!question.trim())return;const q=question;const history=messages.slice(-8).map(m=>({role:m.role,content:m.text.slice(0,4000)}));setQuestion('');setMessages(m=>[...m,{role:'user',text:q}]);setBusy(true);try{const r=await fetch('/api/ask?mode=edge-agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:q,history}),signal:AbortSignal.timeout(115000)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessages(m=>[...m,{role:'assistant',text:d.answer,evidence:d.evidence}]);}catch(e:any){setMessages(m=>[...m,{role:'assistant',text:e.name==='TimeoutError'?'The request timed out. Try a narrower question.':e.message||'Edge agent unavailable.'}]);}finally{setBusy(false);}}
 if(!open)return null;
 return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="drawer" role="dialog" aria-modal="true" aria-label="Ask Edge" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><strong>Ask Edge</strong><span>DeepSeek assistant · SQL agent tool</span></div><button onClick={onClose} aria-label="Close assistant"><X/></button></div><div className="chat"><p>Your questions, dataset definitions and bounded query results are sent to DeepSeek. The assistant can run read-only queries.</p>{configured===false?<p role="status">The agents are not activated yet. Configure DEEPSEEK_API_KEY in Vercel.</p>:null}{!messages.length?<p>Ask about transactions, rent, urban renewal, demographics, economics or elections.</p>:null}{messages.map((m,i)=><div className={'bubble '+(m.role==='assistant'?'edge':'user')} key={i}><pre>{m.text}</pre>{m.evidence?.map((e,j)=><details key={j}><summary>SQL evidence {j+1}{e.result?` · ${e.result.rowCount} returned rows`:''}</summary><pre>{e.sql||e.clarification}</pre><p>{e.explanation}</p>{e.result?<p>{e.result.elapsedMs} ms{e.result.truncated?' · Query result capped at 200 rows':''}{e.result.modelSampleTruncated?' · Model received a smaller bounded sample':''}</p>:null}</details>)}</div>)}{busy?<div className="bubble edge" role="status">Edge is consulting the SQL agent and checking database evidence…</div>:null}</div><form className="ask-form" onSubmit={e=>{e.preventDefault();void ask();}}><textarea aria-label="Question for Edge" maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="שאל על הנתונים או השווה בין אזורים"/><button disabled={busy||configured!==true||!question.trim()}>Send</button></form></aside></div>;
}
