import {useEffect,useRef,useState} from 'react';
import './workflow.css';
type Mutate=(body:any)=>Promise<boolean>;
const stages:Record<string,string>={Saved:'נשמר',Researching:'מחקר',Contacted:'נוצר קשר','Visit Scheduled':'ביקור נקבע',Visited:'בוצע ביקור',Negotiating:'משא ומתן','Due Diligence':'בדיקות נאותות',Offer:'הצעה',Closed:'נסגר',Rejected:'נדחה'};
const ddLabels:Record<string,string>={unknown:'לא נבדק',in_progress:'בבדיקה',verified:'אומת לפי המקורות המצורפים',issue:'נמצא סיכון',not_applicable:'לא רלוונטי'};
const taskLabels:Record<string,string>={todo:'לביצוע',in_progress:'בטיפול',done:'בוצע',cancelled:'בוטל'};
const typeLabels:Record<string,string>={base:'בסיס',conservative:'שמרני',upside:'אופטימי',custom:'מותאם'};
const date=(v:any)=>v?String(v).slice(0,10):'';
const money=(n:any)=>n==null?'לא ידוע':'₪'+Math.round(Number(n)).toLocaleString('he-IL');
const defaults=(ask:number|null)=>({purchasePriceNis:ask??'',purchaseTaxNis:0,legalFeesNis:15000,brokerFeesNis:0,appraisalFeesNis:2500,renovationNis:50000,furnishingNis:0,otherAcquisitionNis:0,loanAmountNis:ask==null?'':Math.round(ask*.5),annualInterestRatePct:4.5,loanTermYears:25,expectedMonthlyRentNis:0,vacancyPct:5,annualMaintenanceNis:6000,annualOtherOperatingNis:0,exitYears:5,annualAppreciationPct:2.5,exitPriceNis:'',saleCostsPct:1.5,saleTaxNis:0,targetAnnualReturnPct:8,evidence:{notes:'',sourceUrl:'',observedAt:''}});
const fields=[['purchasePriceNis','מחיר רכישה','רכישה'],['purchaseTaxNis','מס רכישה','רכישה'],['legalFeesNis','עו״ד','רכישה'],['brokerFeesNis','תיווך','רכישה'],['appraisalFeesNis','שמאות','רכישה'],['renovationNis','שיפוץ','רכישה'],['furnishingNis','ריהוט','רכישה'],['otherAcquisitionNis','עלויות רכישה נוספות ורזרבה','רכישה'],['loanAmountNis','סכום הלוואה','מימון'],['annualInterestRatePct','ריבית שנתית %','מימון'],['loanTermYears','תקופת הלוואה בשנים','מימון'],['expectedMonthlyRentNis','שכירות חודשית','תפעול'],['vacancyPct','שיעור זמן ללא שוכר %','תפעול'],['annualMaintenanceNis','תחזוקה שנתית','תפעול'],['annualOtherOperatingNis','הוצאות תפעול נוספות בשנה','תפעול'],['exitYears','אופק יציאה בשנים','יציאה'],['annualAppreciationPct','שינוי ערך שנתי %','יציאה'],['exitPriceNis','מחיר יציאה מפורש — אופציונלי','יציאה'],['saleCostsPct','עלויות מכירה %','יציאה'],['saleTaxNis','מס במכירה','יציאה'],['targetAnnualReturnPct','תשואת יעד שנתית %','יציאה']];
const outputs=[['totalAcquisitionCostNis','עלות כוללת','money'],['equityRequiredNis','הון עצמי נדרש','money'],['monthlyDebtServiceNis','החזר חודשי','money'],['monthlyCashFlowNis','תזרים חודשי','money'],['grossYieldPct','תשואה ברוטו','pct'],['netYieldPct','תשואה נטו','pct'],['cashOnCashPct','תשואה על ההון','pct'],['irrPct','IRR שנתי','pct'],['projectedExitValueNis','שווי יציאה','money'],['projectedProfitNis','רווח חזוי','money'],['breakEvenMonthlyRentNis','שכירות לאיזון','money'],['maxPurchasePriceForTargetReturnNis','מחיר מרבי לתשואת היעד','money']];
const display=(n:any,kind:string)=>n==null?'לא ידוע':kind==='pct'?Number(n).toFixed(2)+'%':money(n);
const hints:Record<string,string>={Saved:'אמת את המודעה, הכתובת והזמינות. פתח משימה אם חסר מקור מדויק.',Researching:'בדוק התאמת עסקאות וסיכונים; תעד מקור לכל ממצא.',Contacted:'תעד שיחת מוכר, מחיר וציפיות; קבע ביקור.','Visit Scheduled':'הכן שאלות ותעד מצב דירה ובניין בביקור.',Visited:'עדכן עלויות שיפוץ, שכירות והנחות מימון לפי הממצאים.',Negotiating:'השווה תרחישים ומחיר מרבי, והגדר תנאים להצעה.','Due Diligence':'השלם מקורות לזכויות, היתר, בניין ומימון. ביצוע משימה אינו אימות משפטי.',Offer:'בדוק עלות כוללת, רזרבה וסיכונים פתוחים לפני החלטה.',Closed:'תעד את השלמת העסקה והמסמכים.',Rejected:'שמור את סיבת הדחייה כדי ללמוד ולהשוות למועמדים אחרים.'};
function DecisionReview({deal,listingId,scenarios,selected,onSelect,offer,dirty,busy}:{deal:any;listingId:string;scenarios:any[];selected:string;onSelect:(s:any)=>void;offer:string;dirty:boolean;busy:boolean}){
 const [review,setReview]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const request=useRef(0);
 const saved=scenarios.find(x=>x.id===selected);
 const load=async(preview=false)=>{const token=++request.current;setLoading(true);setError('');setReview(null);try{
  const params=new URLSearchParams({mode:'decision_review',deal_id:deal.id,listing_id:listingId,scenario_id:selected});if(preview)params.set('offer_price_nis',offer);
  const r=await fetch('/api/opportunities?'+params,{cache:'no-store'}),j=await r.json();if(!r.ok||j.version!=='decision-review-v1'||j.scenarioId!==selected||j.dealId!==deal.id||!j.financials||!Array.isArray(j.checks))throw Error('לא ניתן לטעון את סיכום ההחלטה');if(token===request.current)setReview(j);
 }catch(e:any){if(token===request.current)setError(e.message)}finally{if(token===request.current)setLoading(false)}};
 useEffect(()=>{setReview(null);setError('');if(saved)void load();return()=>{request.current++}},[selected,saved?.updated_at,deal.updated_at,scenarios]);
 const stale=review?.basis==='offer_preview'&&review.financials.purchasePriceNis!==Number(offer);
 return <section className="panel wf-decision" aria-label="סיכום לפני הצעה"><h3>סיכום לפני הצעה</h3><label>תרחיש לסיכום<select value={selected} onChange={e=>onSelect(scenarios.find(x=>x.id===e.target.value))}><option value="">בחר תרחיש שמור</option>{scenarios.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
 {!saved&&<p>שמור ובחר תרחיש כדי לבדוק עלות, מימון וסיכונים לפני הצעה.</p>}{dirty&&<p className="wf-warning">יש שינויים שלא נשמרו בהנחות. הסיכום משתמש בתרחיש השמור בלבד.</p>}
 {saved&&<div className="wf-actions"><button disabled={busy||loading||!offer.trim()||!Number.isFinite(Number(offer))||Number(offer)<=0} onClick={()=>void load(true)}>בדוק הצעה ללא שמירה</button><button disabled={busy||loading} onClick={()=>void load()}>חזור לסיכום התרחיש השמור</button><span>מחיר הצעה לבדיקה: {offer?money(offer):'הזן מחיר בשדה מחיר הצעה'}</span></div>}
 {loading&&<p role="status">טוען סיכום החלטה…</p>}{error&&<div role="alert">{error}<button onClick={()=>void load()}>נסה לטעון סיכום שוב</button></div>}{stale&&<p role="status">מחיר ההצעה השתנה. בדוק שוב כדי להציג תוצאה תואמת.</p>}
 {review&&!stale&&<><p>{review.basis==='offer_preview'?'תצוגת הצעה בלבד — לא נשמרה':'תרחיש שמור'} · {review.scenarioName} · {review.calculationVersion}</p><div className="wf-output">{[['purchasePriceNis','מחיר שנבדק'],['totalAcquisitionCostNis','עלות רכישה כוללת'],['equityRequiredNis','הון עצמי נדרש'],['loanAmountNis','הלוואה לפי ההנחה'],['monthlyDebtServiceNis','החזר חודשי'],['monthlyCashFlowNis','תזרים חודשי'],['maxPurchasePriceForTargetReturnNis','מחיר מרבי לפי מודל התשואה'],['otherAcquisitionAndReserveNis','עלויות נוספות ורזרבה יחד']].map(([key,label])=><div key={key}><span>{label}</span><strong>{money(review.financials[key])}</strong></div>)}</div>
 <p>IRR שנתי: {display(review.financials.irrPct,'pct')} · יעד: {display(review.financials.targetAnnualReturnPct,'pct')}</p>
 <ul>{review.flags.aboveModelPrice===true&&<li>מחיר הרכישה מעל המחיר המרבי במודל.</li>}{review.flags.belowTargetReturn===true&&<li>התשואה בתרחיש נמוכה מהיעד שהוגדר.</li>}{review.flags.negativeCashFlow===true&&<li>התזרים החודשי בתרחיש שלילי.</li>}</ul>
 <h4>{review.unresolvedCheckCount} בדיקות דורשות בירור</h4><ul>{review.checks.filter((x:any)=>x.needsReview).map((x:any)=><li key={x.id}>{x.label} · {ddLabels[x.status]||'מצב לא ידוע'}{x.status==='verified'&&' · חסר ממצא או מקור מתוארך'}</li>)}{review.missingChecks.length>0&&<li>חסרות {review.missingChecks.length} בדיקות ברשימת הבדיקות של התיק.</li>}</ul>
 <h4>משימות פתוחות</h4>{review.openTasks===null?<p>מידע המשימות אינו זמין.</p>:review.openTasks.length===0?<p>אין משימות פתוחות מתועדות.</p>:<ul>{review.openTasks.map((x:any)=><li key={x.id}>{x.title} · {x.assignee||'ללא אחראי'} · {x.dueDate||'ללא מועד'}{x.overdue&&' · המועד עבר'}</li>)}</ul>}
 <details><summary>מקורות הבדיקות המתועדות</summary>{review.checks.filter((x:any)=>x.sources.length).map((x:any)=><div key={x.id}><strong>{x.label}</strong>{x.sources.map((source:any,i:number)=><p key={i}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> · {source.observedAt||'ללא תאריך'}</p>)}</div>)}</details>
 {review.assumptionEvidence?.sourceUrl&&<p><a href={review.assumptionEvidence.sourceUrl} target="_blank" rel="noreferrer">מקור הנחות התרחיש</a> · {review.assumptionEvidence.observedAt||'ללא תאריך'}</p>}<p>פעולה הבאה: {review.nextAction||'טרם הוגדרה'}</p><ul className="wf-warning">{review.evidence.notes.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul></>}
 </section>;
}
function DdEditor({item,dealId,mutate,onTask,busy}:{item:any;dealId:string;mutate:Mutate;onTask:()=>void;busy:boolean}){
 const [status,setStatus]=useState(item.status),[notes,setNotes]=useState(item.notes||''),[evidence,setEvidence]=useState<any[]>(item.evidence||[]);
 return <article className="wf-dd-item"><h4>{item.label}</h4><label>מצב בדיקה<select aria-label={'מצב בדיקה: '+item.label} value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(ddLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>ממצאים ותוצאה<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{evidence.map((x,i)=><div className="wf-source" key={i}><div className="wf-fields">{[['title','כותרת המקור','text'],['url','קישור למקור','url'],['observedAt','תאריך בדיקת המקור','date']].map(([key,label,type])=><label key={key}>{label}<input type={type} value={x[key]||''} onChange={e=>setEvidence(a=>a.map((old,n)=>n===i?{...old,[key]:e.target.value}:old))}/></label>)}</div><button onClick={()=>setEvidence(a=>a.filter((_,n)=>n!==i))}>הסר מקור מהטיוטה</button>{x.url&&/^https?:\/\//i.test(x.url)&&<a href={x.url} target="_blank" rel="noreferrer">פתח מקור</a>}</div>)}<div className="wf-actions"><button onClick={()=>setEvidence(a=>[...a,{title:'',url:'',observedAt:''}])}>הוסף מקור</button><button disabled={busy} onClick={()=>mutate({action:'update_dd',deal_id:dealId,item_id:item.id,status,notes,evidence})}>שמור בדיקה</button><button onClick={onTask}>פתח משימה להשלמה</button></div>{status==='verified'&&<p>אימות מחייב ממצא ומקור. זהו תיעוד שלך, לא אישור אוטומטי של זכויות או בדיקה מקצועית.</p>}</article>;
}
function TaskEditor({task,dd,dealId,mutate,busy,onSaved}:{task:any;dd:any[];dealId:string;mutate:Mutate;busy:boolean;onSaved:()=>void}){
 const [f,setF]=useState<any>({...task,due_date:date(task.due_date),observed_at:date(task.observed_at)});const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));
 return <form className="wf-task-editor" onSubmit={async e=>{e.preventDefault();if(await mutate({...f,action:'save_task',deal_id:dealId,task_id:f.id}))onSaved()}}><div className="wf-fields">{[['title','משימה','text'],['assignee','אחראי','text'],['due_date','מועד לביצוע','date'],['source_url','קישור למקור המשימה','url'],['observed_at','תאריך בדיקה','date']].map(([key,label,type])=><label key={key}>{label}<input required={key==='title'} type={type} value={f[key]||''} onChange={e=>set(key,e.target.value)}/></label>)}<label>מצב משימה<select aria-label="מצב משימה" value={f.status||'todo'} onChange={e=>set('status',e.target.value)}>{Object.entries(taskLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>בדיקה קשורה<select aria-label="בדיקה קשורה" value={f.dd_item_id||''} onChange={e=>set('dd_item_id',e.target.value)}><option value="">ללא</option>{dd.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label></div><label>תוצאה / מה נמצא<textarea required={f.status==='done'} value={f.result||''} onChange={e=>set('result',e.target.value)}/></label><p>סימון משימה כבוצעה אינו משנה את מצב בדיקת הנאותות ואינו מאמת זכויות.</p><div className="wf-actions"><button disabled={busy}>שמור משימה</button><button type="button" onClick={onSaved}>ביטול</button></div></form>;
}
export default function DealWorkspace({listingId,dealId,section,askingPrice,gaps=[]}:{listingId:string;dealId?:string|null;section:'deal'|'notes'|'dd'|'timeline';askingPrice:number|null;gaps?:string[]}){
 const [bundle,setBundle]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [note,setNote]=useState(''),[category,setCategory]=useState('general'),[noteSource,setNoteSource]=useState(''),[nextAction,setNextAction]=useState(''),[offer,setOffer]=useState('');
 const [selected,setSelected]=useState(''),[scenario,setScenario]=useState<any>(()=>defaults(askingPrice)),[name,setName]=useState('בסיס'),[type,setType]=useState('base'),[primary,setPrimary]=useState(true),[reviewed,setReviewed]=useState(false),[dirty,setDirty]=useState(false);
 const [task,setTask]=useState<any>(null),[ddLabel,setDdLabel]=useState(''),[stage,setStage]=useState(''),[reason,setReason]=useState('');const serial=useRef(0),initialized=useRef(false);
 const select=(x:any)=>{setSelected(x?.id||'');setScenario({...defaults(askingPrice),...(x?.assumptions||{}),evidence:{notes:'',sourceUrl:'',observedAt:'',...(x?.assumptions?.evidence||{})}});setName(x?.name||'תרחיש חדש');setType(x?.scenario_type||'custom');setPrimary(x?.is_primary??false);setReviewed(false);setDirty(false)};
 const load=async()=>{const token=++serial.current;try{const r=await fetch('/api/opportunities?mode=deal&'+'listing_id='+encodeURIComponent(listingId)+(dealId?'&deal_id='+encodeURIComponent(dealId):''),{cache:'no-store'});if(token!==serial.current)return;if(r.status===404){setBundle(null);return;}const j=await r.json();if(!r.ok||!j.deal?.id||!Array.isArray(j.scenarios)||!Array.isArray(j.dueDiligence))throw Error('לא ניתן לטעון את תיק העסקה');setBundle(j);setNextAction(j.deal.next_action||'');setOffer(j.deal.offer_price_nis==null?'':String(j.deal.offer_price_nis));setStage(j.deal.stage==='Lead'?'Saved':j.deal.stage);if(!initialized.current){const first=j.scenarios.find((x:any)=>x.is_primary)||j.scenarios[0];if(first)select(first);initialized.current=true;}return j;}catch(e:any){if(token===serial.current)setError(e.message);throw e;}finally{if(token===serial.current)setLoading(false)}};
 useEffect(()=>{initialized.current=false;setLoading(true);setBundle(null);setError('');setSelected('');setScenario(defaults(askingPrice));void load().catch(()=>{});return()=>{serial.current++}},[listingId,dealId]);
 const mutate:Mutate=async body=>{setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/opportunities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'workflow',...body})});const j=await r.json();if(!r.ok||j.ok!==true)throw Error(j.error||'השמירה נכשלה');if(body.action==='save_scenario'){setSelected(j.data.id);setDirty(false);setReviewed(false);}try{await load();setNotice('נשמר בהצלחה')}catch{setError('');setNotice('הפעולה נשמרה, אך טעינת התיק מחדש נכשלה. רענן כדי לוודא את התוצאה.')}return true;}catch(e:any){setError(e.message);return false;}finally{setBusy(false)}};
 const feedback=<>{error&&<div className="wf-alert" role="alert">הפעולה לא הושלמה: {error}<button onClick={()=>{setError('');void load().catch(()=>{})}}>טען תיק מחדש</button></div>}{notice&&<p role="status">{notice}</p>}</>;
 if(loading)return <div className="workflow-loading">טוען תיק עסקה…</div>;
 if(!bundle)return <div className="workflow-start">{feedback}<h3>התחל תיק עסקה</h3><p>כאן מנהלים בדיקות, משימות, תרחישים והצעה. שמירה למעקב אינה יוצרת תיק.</p>{!error&&<button className="wf-primary" disabled={busy} onClick={()=>mutate({action:'create_deal',listing_id:listingId})}>צור Deal</button>}</div>;
 const deal=bundle.deal,dd=bundle.dueDiligence||[],tasks=bundle.tasks||[],saved=bundle.scenarios.find((x:any)=>x.id===selected);
 const summary=<section className="panel wf-summary"><h3>מה נשאר להחלטה?</h3><p>{hints[deal.stage]||hints.Saved}</p><div className="wf-summary-metrics"><span>{dd.filter((x:any)=>!['verified','not_applicable'].includes(x.status)).length} בדיקות פתוחות</span><span>{tasks.filter((x:any)=>!['done','cancelled'].includes(x.status)).length} משימות פתוחות</span><span>{bundle.scenarios.length} תרחישים שמורים</span></div>{gaps.length>0&&<details><summary>מידע שדורש השלמה</summary><ul>{gaps.map((x,i)=><li key={i}>{x}</li>)}</ul></details>}<p>פעולה הבאה: {deal.next_action||'טרם הוגדרה'}</p></section>;
 const taskPanel=<section className="panel"><h3>משימות ופעולות</h3>{bundle.taskSchemaReady===false?<p role="alert">הרחבת המשימות עדיין אינה זמינה. בדיקות והערות נשארות זמינות.</p>:<><button onClick={()=>setTask({title:'',status:'todo'})}>משימה חדשה</button>{gaps.map((x,i)=><button key={i} onClick={()=>setTask({title:x,status:'todo'})}>הפוך למשימה: {x}</button>)}{task&&<TaskEditor key={task.id||task.title} task={task} dd={dd} dealId={deal.id} mutate={mutate} busy={busy} onSaved={()=>setTask(null)}/>}<ul className="wf-task-list">{tasks.map((x:any)=><li key={x.id}><strong>{x.title}</strong><span>{taskLabels[x.status]} · {x.assignee||'ללא אחראי'} · {date(x.due_date)||'ללא מועד'}</span>{x.result&&<p>{x.result}</p>}<button onClick={()=>setTask(x)}>ערוך משימה</button></li>)}</ul></>}</section>;
 if(section==='dd')return <div className="wf-layout">{feedback}{summary}{taskPanel}<section className="panel"><h3>בדיקות נאותות ומקורות</h3><form className="wf-actions" onSubmit={async e=>{e.preventDefault();if(await mutate({action:'create_dd_item',deal_id:deal.id,label:ddLabel}))setDdLabel('')}}><label>בדיקה חדשה<input required value={ddLabel} onChange={e=>setDdLabel(e.target.value)}/></label><button disabled={busy||!ddLabel.trim()}>הוסף בדיקה</button></form>{dd.map((x:any)=><DdEditor key={x.id+':'+x.updated_at} item={x} dealId={deal.id} mutate={mutate} busy={busy} onTask={()=>setTask({title:'השלם: '+x.label,dd_item_id:x.id,status:'todo'})}/>)}</section></div>;
 if(section==='notes')return <div className="wf-layout">{feedback}<section className="panel"><h3>הוסף הערה</h3><label>סוג הערה<select aria-label="סוג הערה" value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries({general:'כללי',seller:'שיחת מוכר',visit:'ביקור',legal:'זכויות ומשפטי',building:'בניין',renovation:'שיפוץ',financing:'מימון',renewal:'התחדשות'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><textarea aria-label="תוכן הערה" value={note} onChange={e=>setNote(e.target.value)} placeholder="מה גילית? מה צריך לזכור?"/><label>קישור מקור להערה<input type="url" value={noteSource} onChange={e=>setNoteSource(e.target.value)}/></label><button disabled={busy||!note.trim()} onClick={async()=>{if(await mutate({action:'save_note',deal_id:deal.id,category,content:note,evidence_url:noteSource})){setNote('');setNoteSource('')}}}>שמור הערה</button></section><section className="panel"><h3>הערות שמורות</h3>{(bundle.notes||[]).map((x:any)=><article className="wf-dd-item" key={x.id}><strong>{x.category} · {date(x.created_at)}</strong><p>{x.content}</p>{x.evidence_url&&/^https?:\/\//i.test(x.evidence_url)&&<a href={x.evidence_url} target="_blank" rel="noreferrer">מקור ההערה</a>}<button disabled={busy} onClick={()=>{if(window.confirm('למחוק את ההערה? לא ניתן לשחזר אותה דרך הממשק.'))void mutate({action:'delete_note',deal_id:deal.id,note_id:x.id})}}>מחק הערה</button></article>)}</section></div>;
 if(section==='timeline')return <div className="wf-layout">{feedback}<section className="panel"><h3>היסטוריית תיק</h3>{(bundle.events||[]).map((x:any)=><article className="wf-dd-item" key={x.id}><strong>{x.summary||x.event_type}</strong><p>{new Date(x.event_at).toLocaleString('he-IL')}</p>{x.payload?.rejectionReason&&<p>סיבת דחייה: {x.payload.rejectionReason}</p>}</article>)}</section></div>;
 return <div className="wf-layout">{feedback}{summary}<DecisionReview deal={deal} listingId={listingId} scenarios={bundle.scenarios} selected={selected} onSelect={select} offer={offer} dirty={dirty} busy={busy}/><section className="panel"><h3>שלב ופעולה הבאה</h3><div className="wf-fields"><label>שלב עסקה<select aria-label="שלב עסקה" value={stage} onChange={e=>setStage(e.target.value)}>{Object.entries(stages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{stage==='Rejected'&&<label>סיבת דחייה<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>}<button disabled={busy||(stage==='Rejected'&&!reason.trim())} onClick={()=>mutate({action:'set_stage',deal_id:deal.id,stage,rejection_reason:reason})}>שמור שלב</button><button onClick={()=>{setStage(deal.stage==='Lead'?'Saved':deal.stage);setReason('')}}>בטל שינוי שלב</button><label>הפעולה הבאה<input value={nextAction} onChange={e=>setNextAction(e.target.value)}/></label><button disabled={busy} onClick={()=>mutate({action:'next_action',deal_id:deal.id,next_action:nextAction})}>שמור פעולה הבאה</button><label>מחיר הצעה<input type="number" min="0" value={offer} onChange={e=>setOffer(e.target.value)}/></label><button disabled={busy} onClick={()=>mutate({action:'set_offer',deal_id:deal.id,offer_price_nis:offer===''?null:Number(offer)})}>שמור הצעה</button></div><p>שינוי שלב הוא תיעוד ידני; הוא אינו מאשר שהמסמכים או הזכויות נבדקו.</p></section>{taskPanel}
 <section className="panel"><h3>תרחיש והנחות</h3><div className="wf-fields"><label>תרחיש שמור<select aria-label="תרחיש שמור" value={selected} onChange={e=>select(bundle.scenarios.find((x:any)=>x.id===e.target.value))}><option value="">תרחיש חדש</option>{bundle.scenarios.map((x:any)=><option value={x.id} key={x.id}>{x.name}{x.is_primary?' · ראשי':''}</option>)}</select></label><label>שם תרחיש<input value={name} onChange={e=>{setName(e.target.value);setDirty(true);setReviewed(false)}}/></label><label>סוג תרחיש<select aria-label="סוג תרחיש" value={type} onChange={e=>{setType(e.target.value);setDirty(true);setReviewed(false)}}>{Object.entries(typeLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></div><p className="wf-warning">הערכים ההתחלתיים הם הנחות לדוגמה, לא נתוני נכס מאומתים. מסים, שכירות, ריבית ושיפוץ דורשים בירור. אפס הוא הנחה מפורשת, לא מידע חסר. שינוי סוג תרחיש אינו מייצר תחזית אוטומטית.</p>
 {['רכישה','מימון','תפעול','יציאה'].map(group=><fieldset key={group}><legend>{group}</legend><div className="wf-fields">{fields.filter(x=>x[2]===group).map(([key,label])=><label key={key}>{label}<input type="number" required={key!=='exitPriceNis'} step="any" value={scenario[key]??''} onChange={e=>{setScenario((a:any)=>({...a,[key]:e.target.value}));setDirty(true);setReviewed(false)}}/></label>)}</div></fieldset>)}
 <label>מקורות והסבר להנחות<textarea value={scenario.evidence?.notes||''} onChange={e=>{setScenario((a:any)=>({...a,evidence:{...a.evidence,notes:e.target.value}}));setDirty(true);setReviewed(false)}}/></label><div className="wf-fields"><label>מקור להנחות<input type="url" value={scenario.evidence?.sourceUrl||''} onChange={e=>{setScenario((a:any)=>({...a,evidence:{...a.evidence,sourceUrl:e.target.value}}));setDirty(true);setReviewed(false)}}/></label><label>תאריך בירור<input type="date" value={date(scenario.evidence?.observedAt)} onChange={e=>{setScenario((a:any)=>({...a,evidence:{...a.evidence,observedAt:e.target.value}}));setDirty(true);setReviewed(false)}}/></label></div><div className="wf-actions"><label><input type="checkbox" checked={primary} onChange={e=>setPrimary(e.target.checked)}/>הגדר כתרחיש ראשי</label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>בדקתי את ההנחות, כולל ערכי אפס</label><button className="wf-primary" disabled={busy||!reviewed} onClick={()=>mutate({action:'save_scenario',deal_id:deal.id,scenario_id:selected||undefined,name,scenario_type:type,is_primary:primary,assumptions:scenario})}>חשב ושמור תרחיש</button></div></section>
 <section className="panel"><h3>תוצאות שמורות — {saved?.name||'אין תרחיש נבחר'}</h3>{dirty&&<p role="status">הטיוטה השתנתה. התוצאות להלן שייכות לגרסה השמורה, לא לשינויים שטרם חושבו.</p>}{saved&&<><p>{saved.calculation_version} · {date(saved.calculated_at)}</p><div className="wf-output">{outputs.map(([key,label,kind])=><div key={key}><span>{label}</span><strong>{display(saved.outputs?.[key],kind)}</strong></div>)}</div></>}</section><section className="panel"><h3>השוואת תרחישים שמורים</h3><p>ההשוואה משתמשת בתוצאות שחושבו בשרת. אין חישוב פיננסי בדפדפן.</p><div className="table-wrap"><table><thead><tr><th>מדד</th>{bundle.scenarios.map((x:any)=><th key={x.id}>{x.name}</th>)}</tr></thead><tbody>{outputs.map(([key,label,kind])=><tr key={key}><th>{label}</th>{bundle.scenarios.map((x:any)=><td key={x.id}>{display(x.outputs?.[key],kind)}</td>)}</tr>)}</tbody></table></div></section></div>;
}
