import {Component,useEffect,useState,type ReactNode} from 'react';
import {AlertTriangle,ArrowRight,Building2,ExternalLink,RefreshCw,Search} from 'lucide-react';
import './renewal-projects.css';
const types:Record<string,string>={pinui_binui:'פינוי־בינוי',tama_38_1:'תמ״א 38 — חיזוק',tama_38_2:'תמ״א 38 — הריסה ובנייה',infill:'עיבוי',building_renewal:'התחדשות בניינית',unknown:'מסלול לא אומת'};
const kinds:Record<string,string>={official:'מקור רשמי',developer:'דיווח יזם',secondary:'מקור משני',manual:'מידע ידני'};
const memberships:Record<string,string>={verified:'הכללה מאומתת',verified_parcel:'חלקה מקושרת',reported:'הכללה מדווחת',unverified:'הכללה לא אומתה',excluded:'לא נכלל לפי המקור'};
const labels:Record<string,string>={existing_units:'יח״ד קיימות',planned_units:'יח״ד מתוכננות',marketed_units:'יח״ד לשיווק',signatures_pct:'שיעור חתימות',permit_forecast:'תחזית להיתר',planning_stage:'שלב תכנוני',historical_scope:'תיאור היסטורי',scope_conflict:'סתירה בגבולות הפרויקט',stakeholders:'גורמים מעורבים',benefits:'תמורות מדווחות',address_scope:'גבולות וכתובות'};
const money=(v:any)=>v==null?'—':'₪'+Math.round(Number(v)).toLocaleString('he-IL');
const date=(v:any)=>v?new Date(v).toLocaleDateString('he-IL'):'מועד פרסום לא ידוע';
const safeUrl=(v:any)=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:undefined;}catch{return undefined;}};
function Source({url,title}:{url:string;title:string}){const href=safeUrl(url);return href?<a href={href} target="_blank" rel="noreferrer">{title}<ExternalLink size={13}/></a>:<span>{title}</span>;}
function Empty({children}:{children:any}){return <div className="rp-empty"><AlertTriangle size={18}/>{children}</div>;}
function Fact({fact}:{fact:any}){return <div className={'rp-fact '+fact.evidence_status}><strong>{labels[fact.fact_key]||fact.fact_key}</strong><p>{typeof fact.value==='object'?JSON.stringify(fact.value):String(fact.value)}{fact.fact_key==='signatures_pct'?'%':''}</p><small>{kinds[fact.source_kind]} · {fact.source_date?new Date(fact.source_date).toLocaleDateString('he-IL',{month:'long',year:'numeric'}):'מועד פרסום לא ידוע'}{fact.evidence_status==='conflicting'?' · סתירה פתוחה':''}</small><Source url={fact.source_url} title={fact.source_title}/><small>{fact.locator} · נבדק {date(fact.checked_at)}</small></div>;}
class ProjectBoundary extends Component<{children:ReactNode},{failed:boolean}> {
 state={failed:false};
 static getDerivedStateFromError(){return {failed:true};}
 render(){return this.state.failed?<section className="screen rp-screen"><Empty>לא ניתן להציג את הפרויקט. אפשר לנסות שוב או לחזור לרשימה.</Empty><button onClick={()=>this.setState({failed:false})}>נסה שוב</button> <a href="#/renewal">כל הפרויקטים</a></section>:this.props.children;}
}
type ProjectProps={projectId?:string|null;onOpenListing:(x:any)=>void};
export default function RenewalProjects(props:ProjectProps){return <ProjectBoundary key={props.projectId||'directory'}><ProjectContent key={props.projectId||'directory'} {...props}/></ProjectBoundary>;}
function ProjectContent({projectId,onOpenListing}:{projectId?:string|null;onOpenListing:(x:any)=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[city,setCity]=useState('');
 const [tab,setTab]=useState('overview');
 const load=async(signal?:AbortSignal)=>{setBusy(true);setError('');try{const url='/api/renewal?view=profiles'+(projectId?'&id='+encodeURIComponent(projectId):'');const r=await fetch(url,{signal});const x=await r.json();if(!r.ok)throw new Error(x.message||x.error||'הטעינה נכשלה');if(projectId?(!x.data?.project||x.data.project.id!==projectId):!Array.isArray(x.data))throw new Error('השרת החזיר מידע שאינו מתאים למסך');setData(x.data);}catch(e:any){if(e.name!=='AbortError')setError('לא ניתן לטעון את הפרויקטים. '+e.message);}finally{if(!signal?.aborted)setBusy(false);}};
 useEffect(()=>{const controller=new AbortController();setData(null);setTab('overview');void load(controller.signal);return()=>controller.abort();},[projectId]);
 if(error)return <section className="screen rp-screen"><a href="#/renewal">כל הפרויקטים</a><Empty>{error}</Empty><button onClick={()=>load()}>נסה שוב</button></section>;
 if(!data)return <section className="screen rp-screen"><RefreshCw className="spin"/> טוען פרויקטים…</section>;
 if(!projectId){
  const rows=Array.isArray(data)?data:[];const cities=[...new Set<string>(rows.map(x=>x.city).filter(Boolean))];
  const filtered=rows.filter(x=>(!city||x.city===city)&&(!query||[x.project_name,x.plan_number,x.developer,x.neighborhood,x.city].join(' ').includes(query)));
  return <section className="screen rp-screen"><div className="rp-heading"><div><span className="eyebrow">מחקר התחדשות עירונית</span><h1>פרויקטים</h1><p>מהאזור לפרויקט, לבניין ולדירה — עם מקורות וסטטוס ברור.</p></div><button onClick={()=>load()} disabled={busy}><RefreshCw size={15}/>רענן</button></div>
   <div className="rp-filters"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="שם פרויקט, רחוב, יזם או תוכנית" aria-label="חיפוש פרויקטים"/></label><select value={city} onChange={e=>setCity(e.target.value)} aria-label="עיר"><option value="">כל הערים</option>{cities.map(c=><option key={c}>{c}</option>)}</select><span>{filtered.length} פרויקטים</span></div>
   <div className="rp-notice">אישור תוכנית, היתר בנייה ותחילת ביצוע הם שלבים נפרדים. פרויקט בשכונה אינו הוכחה להכללת דירה.</div>
   {!filtered.length?<Empty>לא נמצאו פרויקטים לפי הסינון.</Empty>:<div className="table-wrap"><table className="rp-table"><thead><tr><th>פרויקט</th><th>אזור</th><th>מסלול</th><th>תכנון</th><th>היתר</th><th>מידע ומקורות</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><a className="rp-project-link" href={'#/renewal/'+x.id}><Building2 size={17}/>{x.project_name||x.plan_number||'פרויקט ללא שם'}</a><small>{x.developer||'יזם לא אומת'}</small></td><td>{x.city||'—'}<small>{x.neighborhood||'שיוך שכונה חסר'}</small></td><td>{types[x.project_type]||x.route||'לא אומת'}</td><td>{x.planning_stage||x.status||'לא זמין'}<small>{x.plan_number||'מספר תוכנית חסר'}</small></td><td>{x.permit_stage||(x.permits_count!=null?'דווחו '+x.permits_count+' במקור; לבדוק היתרים':'לא אותר מידע')}</td><td>{x.fact_count?x.fact_count+' ראיות מיוחסות':'רישום מקור; מחקר חסר'}<small>תצפית {date(x.observed_at)}</small></td></tr>)}</tbody></table></div>}
   <details className='panel'><summary>מקורות נוספים שצריך להשלים</summary><p>מקורות בעדיפות גבוהה לחקר כל פרויקט. אלה אינם חיבורים פעילים עד שנאסף ואומת המידע.</p><div className='rp-facts'>{[
 ['גבולות וחלקות','GIS עירוני — גבול מתחם, תוכניות וחלקות. אימות שיוך הבניין קודם לתמחור זכויות.','https://gisserver.haifa.muni.il/arcgiswebadaptor/rest/services/PublicSite/Haifa_Eng_Public/MapServer'],
 ['תוכניות והחלטות','מבא״ת והוועדה המקומית — מספר תוכנית, תשריט, הפקדה, אישור והתנגדויות.','https://mavat.iplan.gov.il/SV3?searchEntity=1'],
 ['תיק בניין והיתרים','מערכת תיקי הבניין — תוכניות היתר, בקשות וטופסי אכלוס לפי בניין.','https://www1.haifa.muni.il/apps/handasasys/images/Instructions.pdf'],
 ['עסקאות מקוריות','רשות המסים — אימות מחיר, מועד, שטח, חלק בעלות וזיהוי גוש־חלקה.','https://www.gov.il/he/departments/targetaudience/taxes-audience-seller-buyer-real-estate'],
 ['טאבו ומסמכי בית משותף','זיהוי משפטי, שטח רשום, הצמדות ושעבודים. נדרשת רכישת מסמכים לפי זיהוי הנכס.','https://www.gov.il/he/service/land_registration_extract'],
 ['מסמכי דיירים ויזם','הסכם ותמורות חתומים, ערבויות, ליווי וחתימות; תחזית יזם תישמר בנפרד מאישור רשמי.','https://www.haifa.muni.il/development-and-construction/urban-planning/urban-renewal/guidelines/']
 ].map(([title,body,url])=><div className='rp-fact' key={title}><strong>{title}</strong><p>{body}</p><Source url={url} title='מקור ושיטת רכישה'/></div>)}</div></details>
  </section>;
 }
 const p=data.project,facts=data.facts||[];
 const currentFact=(key:string)=>facts.find((f:any)=>f.fact_key===key&&f.source_kind==='official')||facts.find((f:any)=>f.fact_key===key&&f.source_kind==='developer');
 const metric=(key:string,fallback:any)=>{const f=currentFact(key);return {value:f?.value??fallback??'—',note:f?kinds[f.source_kind]+' · '+(f.source_date?new Date(f.source_date).toLocaleDateString('he-IL',{month:'long',year:'numeric'}):'מועד לא ידוע'):'נתוני מקור שנקלטו; יש לבדוק תחולה'};};
 const metrics=[['existing_units',p.existing_units],['planned_units',p.planned_units],['signatures_pct',null],['permit_forecast',null]];
 return <section className="screen rp-screen"><nav className="rp-breadcrumbs" aria-label="מיקום באפליקציה"><a href="#/research">מחקר</a><span>/</span><a href="#/renewal">פרויקטים</a><span>/</span><span>{p.project_name}</span></nav>
  <div className="rp-heading"><div><span className="eyebrow">{types[p.project_type]||'מסלול לא אומת'} · {p.city}</span><h1>{p.project_name}</h1><p>{p.developer||'יזם לא אומת'} · {p.neighborhood||'שיוך שכונה חסר'} · {p.plan_number||'מספר תוכנית טרם אומת'}</p>{p.neighborhood_id&&<a href={'#/areas?neighborhoodId='+p.neighborhood_id}>פתיחת האזור במפה</a>}</div><a href="#/renewal" className="rp-return"><ArrowRight size={15}/>כל הפרויקטים</a></div>
  <div className="rp-notice">{p.summary||'רישום מקור קיים. טרם הושלם מחקר פרויקט פרטני.'}</div>
  <div className="rp-kpis">{metrics.map(([key,fallback])=>{const m=metric(String(key),fallback);return <div key={String(key)}><span>{labels[String(key)]}</span><strong>{String(m.value)}{key==='signatures_pct'&&m.value!=='—'?'%':''}</strong><small>{m.note}</small></div>;})}</div>
  <nav className="rp-tabs" aria-label="מידע על הפרויקט">{[['overview','סקירה וסטטוס'],['addresses','כתובות וחלקות'],['market','דירות ועסקאות'],['evidence','מסמכים ומקורות'],['gaps','מידע חסר']].map(([key,label])=><button key={key} aria-pressed={tab===key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
  {tab==='overview'&&<><div className="rp-stages">{[['תכנון',p.planning_stage||p.status],['היתר',p.permit_stage],['ביצוע',p.execution_stage]].map(([label,value])=><section className="panel" key={label}><h3>{label}</h3><p>{value||'לא אומת'}</p></section>)}</div><div className="rp-facts">{facts.filter((f:any)=>['stakeholders','benefits','scope_conflict','historical_scope'].includes(f.fact_key)).map((f:any)=><Fact key={f.id} fact={f}/>)}</div><p className="rp-muted">תחזית היתר אינה מועד פינוי מאושר. אין חישוב אוטומטי של שווי הדירה אחרי ההתחדשות.</p></>}
  {tab==='addresses'&&<><div className="rp-notice">רק כתובת מאומתת בפרויקט או קישור חלקה מפורש מאשרים תחולה. כתובות לבדיקה מוצגות בנפרד.</div>{!data.addresses?.length?<Empty>לא אותרה רשימת כתובות מאומתת לפרויקט.</Empty>:<div className="table-wrap"><table className="rp-table"><thead><tr><th>כתובת</th><th>הכללה</th><th>ראיות</th></tr></thead><tbody>{data.addresses.map((a:any)=><tr key={a.street_name+a.house_number}><td>{a.street_name} {a.house_number}</td><td><span className={'rp-membership '+a.membership}>{memberships[a.membership]}</span></td><td>{a.note}<Source url={a.source_url} title="מקור הקישור / מידע לבדיקה"/></td></tr>)}</tbody></table></div>}{!data.parcels?.length?<Empty>אין עדיין חלקות מקושרות לפרויקט.</Empty>:<p>חלקות: {data.parcels.map((x:any)=>x.gush+' / '+x.helka).join(', ')}</p>}{p.geometry?<p>קיים גבול פרויקט במקור.</p>:<p className="rp-muted">גבול פרויקט טרם נקלט. לא מוצג פוליגון משוער.</p>}{p.map_url&&<Source url={p.map_url} title="מפת מקור"/>}</>}
  {tab==='market'&&<><h3>דירות שנמצאו בכתובות המחקר</h3>{!data.listings?.length?<Empty>לא נמצאו במאגר דירות בכתובות המתועדות לפרויקט.</Empty>:<div className="table-wrap"><table className="rp-table"><thead><tr><th>דירה</th><th>מחיר מבוקש</th><th>מ״ר</th><th>חדרים</th><th>הכללה</th></tr></thead><tbody>{data.listings.map((x:any)=><tr key={x.id}><td><button className="rp-project-link" onClick={()=>onOpenListing({...x,neighborhood_id:p.neighborhood_id,neighborhood:p.neighborhood,city:p.city})}>{x.address}</button><small>{x.status}</small></td><td>{money(x.asking_price)}</td><td>{x.sqm??'—'}</td><td>{x.rooms??'—'}</td><td>{memberships[x.membership]}</td></tr>)}</tbody></table></div>}
   <h3>עסקאות סגורות במאגר</h3>{!data.transactions?.length?<Empty>לא נמצאו עסקאות מקושרות לפי כתובת מדויקת או חלקה. זהו פער כיסוי, ולא הוכחה שלא היו מכירות.</Empty>:<div className="table-wrap"><table className="rp-table"><thead><tr><th>כתובת / תאריך</th><th>מחיר עסקה</th><th>מ״ר / חדרים</th><th>הכללה</th><th>מקור ואיכות</th></tr></thead><tbody>{data.transactions.map((x:any)=><tr key={x.id}><td>{x.address||'כתובת חסרה'}<small>{date(x.deal_date)}</small></td><td>{money(x.price)}</td><td>{x.sqm??'—'} / {x.rooms??'—'}</td><td>{memberships[x.membership]}</td><td>{x.source_id}<small>{x.is_comparable?'עומדת בסינון עסקאות השוואה':'לא אושרה להשוואה'} · חלק בעלות {x.ownership_fraction??'לא ידוע'}</small></td></tr>)}</tbody></table></div>}<p className="rp-muted">מחירי מודעות ומחירי עסקאות מוצגים בנפרד. עסקאות בכתובת שלא אומתה בפרויקט הן מידע לבדיקה.</p></>}
  {tab==='evidence'&&<><Source url={p.source_url} title="מקור רישום הפרויקט"/><div className="rp-facts">{facts.length?facts.map((f:any)=><Fact key={f.id} fact={f}/>):<Empty>לא נוספו עדיין מסמכי מחקר פרטניים. סטטוס המקור מוצג בסקירה.</Empty>}</div></>}
  {tab==='gaps'&&<section className="panel"><h3>מה צריך להשלים לפני החלטת השקעה</h3><ul>{(p.gaps?.length?p.gaps:['רשימת בניינים וחלקות מאומתת','תכנון, היתר וביצוע ברמת הפרויקט','מסמכי יזם, תמורות וערבויות','עסקאות ודירות בעלות זיהוי מדויק']).map((g:string)=><li key={g}>{g}</li>)}</ul><a href="#/data">פתיחת נתונים ומקורות נוספים</a></section>}
 </section>;
}
