import type { VercelRequest,VercelResponse } from '@vercel/node';
import { sql } from '../server/db.js';
export default async function handler(req:VercelRequest,res:VercelResponse){
 if(req.method!=='GET')return res.status(405).json({error:'method_not_allowed'});
 try{
 const areas=await sql`WITH tx AS (SELECT neighborhood_id,count(*) FILTER(WHERE deal_date>=current_date-interval '12 months')::int transactions_12m,percentile_cont(.5) WITHIN GROUP(ORDER BY pp_sqm) FILTER(WHERE pp_sqm BETWEEN 5000 AND 100000) AS avg_price_sqm,percentile_cont(.5) WITHIN GROUP(ORDER BY pp_sqm) FILTER(WHERE pp_sqm BETWEEN 5000 AND 100000 AND deal_date>=current_date-interval '12 months') p1,percentile_cont(.5) WITHIN GROUP(ORDER BY pp_sqm) FILTER(WHERE pp_sqm BETWEEN 5000 AND 100000 AND deal_date>=current_date-interval '24 months' AND deal_date<current_date-interval '12 months') p0,percentile_cont(.5) WITHIN GROUP(ORDER BY pp_sqm) FILTER(WHERE pp_sqm BETWEEN 5000 AND 100000 AND deal_date>=current_date-interval '36 months' AND deal_date<current_date-interval '24 months') p3 FROM transactions WHERE neighborhood_id IS NOT NULL GROUP BY neighborhood_id),rp AS (SELECT neighborhood_id,count(*)::int renewal_projects,coalesce(sum(existing_units),0)::int existing_units,coalesce(sum(planned_units),0)::int planned_units FROM renewal_projects WHERE neighborhood_id IS NOT NULL GROUP BY neighborhood_id) SELECT n.slug id,n.name_he name,c.name_he city,coalesce(tx.avg_price_sqm,0)::float8 avg_price_sqm,CASE WHEN tx.p0>0 THEN 100*(tx.p1/tx.p0-1) ELSE 0 END::float8 change_1y,CASE WHEN tx.p3>0 THEN 100*(tx.p1/tx.p3-1) ELSE 0 END::float8 change_3y,coalesce(tx.transactions_12m,0)::int transactions_12m,coalesce(rp.renewal_projects,0)::int renewal_projects,coalesce(rp.existing_units,0)::int existing_units,coalesce(rp.planned_units,0)::int planned_units,0::int socio_cluster,0::int population FROM neighborhoods n JOIN cities c ON c.id=n.city_id LEFT JOIN tx ON tx.neighborhood_id=n.id LEFT JOIN rp ON rp.neighborhood_id=n.id WHERE n.is_focus=true ORDER BY n.slug`;
 const opportunities=await sql`WITH latest_snap AS (SELECT DISTINCT ON(listing_id) * FROM listing_snapshots ORDER BY listing_id,observed_at DESC),latest_score AS(SELECT DISTINCT ON(entity_id) entity_id,score FROM opportunity_scores WHERE entity_type='listing' ORDER BY entity_id,calculated_at DESC),comps AS(SELECT neighborhood_id,percentile_cont(.5) WITHIN GROUP(ORDER BY pp_sqm) FILTER(WHERE pp_sqm BETWEEN 5000 AND 100000 AND deal_date>=current_date-interval '18 months') comp_pp_sqm,count(*) FILTER(WHERE pp_sqm BETWEEN 5000 AND 100000 AND deal_date>=current_date-interval '18 months')::int comp_count FROM transactions WHERE neighborhood_id IS NOT NULL GROUP BY neighborhood_id) SELECT l.id::text id,l.canonical_address address,n.slug neighborhood_id,n.name_he neighborhood,c.name_he city,s.asking_price_nis::float8 asking_price,s.area_sqm::float8 sqm,s.rooms::float8 rooms,s.floor::text floor,CASE WHEN s.area_sqm>0 THEN (s.asking_price_nis/s.area_sqm)::float8 ELSE 0 END price_sqm,CASE WHEN s.area_sqm>0 AND comps.comp_pp_sqm>0 THEN (s.area_sqm*comps.comp_pp_sqm)::float8 ELSE s.asking_price_nis::float8 END adjusted_value,CASE WHEN s.area_sqm>0 AND comps.comp_pp_sqm>0 THEN (100*(s.area_sqm*comps.comp_pp_sqm-s.asking_price_nis)/(s.area_sqm*comps.comp_pp_sqm))::float8 ELSE 0 END discount_pct,'Live' renewal_stage,coalesce(sig.days_on_market,0)::int days_on_market,CASE WHEN coalesce(sig.days_on_market,0)>120 OR coalesce(sig.price_reductions,0)>=3 THEN 'גבוה מאוד' WHEN coalesce(sig.days_on_market,0)>75 OR coalesce(sig.price_reductions,0)>=2 THEN 'גבוה' WHEN coalesce(sig.days_on_market,0)>35 THEN 'בינוני' ELSE 'נמוך' END seller_motivation,coalesce(comps.comp_count,0)::int comp_count,coalesce(sc.score,50)::int score,coalesce(sig.price_reductions,0)+1 price_points,coalesce(sig.original_asking_price,s.asking_price_nis)::float8 original_price FROM listings l JOIN latest_snap s ON s.listing_id=l.id JOIN neighborhoods n ON n.id=l.neighborhood_id JOIN cities c ON c.id=l.city_id LEFT JOIN latest_score sc ON sc.entity_id=l.id LEFT JOIN listing_seller_signals sig ON sig.listing_id=l.id LEFT JOIN comps ON comps.neighborhood_id=l.neighborhood_id WHERE l.status='active' ORDER BY score DESC LIMIT 100`;
 const sources=await sql`SELECT id,name,kind source_type,(SELECT max(finished_at) FROM ingestion_runs r WHERE r.source_id=data_sources.id AND r.status='success') last_success_at,(SELECT max(finished_at) FROM ingestion_runs r WHERE r.source_id=data_sources.id AND r.status='failed') last_error_at FROM data_sources ORDER BY id`;
 res.status(200).json({mode:'live',generatedAt:new Date().toISOString(),areas,opportunities,sources});
 }catch(e){res.status(503).json({mode:'unavailable',error:String(e)});}
}
